name: Draft Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  draft:
    name: Create or update release draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release Draft
        uses: darioblanco/release-wizard@v3
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
